[project]
name = "aoc"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4",
    "countdown-timer>=0.0.3",
    "lxml>=6.0.2",
    "markdownify>=1.2.2",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
